In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from bs4 import BeautifulSoup
import re
import requests

In [2]:
product_name=[]
distances=[]
emis=[]
final_prices=[]
locations=[]

In [9]:
req_header={
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36",
    "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Referer": "https://www.google.com/"
    }
for i in range(1,500):
    url=f"https://www.cars24.com/buy-used-car/?sort=bestmatch&serveWarrantyCount=true&listingSource=FilterTags&storeCityId={i}"
    response=requests.get(url,headers=req_header)
    html_data=response.text
    soup=BeautifulSoup(html_data)
    product=soup.find_all(class_='sc-ksBlki dxpZAa')
    for i in product:
      product_name.append(i.text)
    distance=soup.find_all(class_='sc-ksBlki knJTXq')
    for i in distance:
      distances.append(i.text)
    emi=soup.find_all(class_='styles_flexItem__2z__J')
    for i in emi:
      emis.append(i.text)
    final_price=soup.find_all(class_='sc-ksBlki dMXwkk')
    for i in final_price:
      final_prices.append(i.text)
    location=soup.find_all(class_='styles_ellipsis__uatjG')
    for i in location:
      locations.append(i.text)

In [10]:
km = [int(re.sub(r'[^0-9]', '', x)) for x in distances if re.search(r'km$', x)]
fuel = [x for x in distances if re.fullmatch(r'Petrol|Diesel|CNG|Electric|Hybrid', x)]
transmission = [x for x in distances if re.fullmatch(r'Manual|Automatic', x)]
registration = [x for x in distances if re.fullmatch(r'[A-Z]{2}-\d{1,2}', x)]

In [11]:
print("Car Name:",product_name)
print("-"*150)
print("Kilometers:",km)
print("-"*150)
print("Fuel:",fuel)
print("-"*150)
print("Transmission:",transmission)
print("-"*150)
print("Registration:",registration)
print("-"*150)
print("EMI:",emis)
print("-"*150)
print("Final Price:",final_prices)
print("-"*150)
print("Location:",locations)

Car Name: ['2019 Maruti Swift', '2015 Hyundai Eon', '2015 Maruti Wagon R 1.0', '2015 Honda Amaze', '2019 Maruti Swift', '2016 Tata Tiago', '2019 Datsun Redi Go', '2019 Maruti Swift', '2016 Hyundai Elite i20', '2015 Honda City', '2014 Hyundai Grand i10', '2018 Datsun Redi Go', '2017 Maruti Wagon R 1.0', '2024 KIA SONET', '2019 Hyundai Grand i10', '2019 MG HECTOR', '2017 Maruti Swift', '2017 Maruti Swift', '2021 Tata PUNCH', '2018 Maruti Wagon R 1.0', '2021 Maruti Swift', '2023 Toyota Glanza', '2019 Ford FREESTYLE', '2017 Renault Kwid', '2016 Maruti Swift', '2022 Maruti Swift', '2019 Tata NEXON', '2022 Tata PUNCH', '2017 Maruti Wagon R 1.0', '2018 Renault Kwid', '2022 Tata NEXON', '2020 Renault TRIBER', '2018 Tata Tiago', '2023 Volkswagen TAIGUN', '2017 Hyundai Creta', '2019 Maruti Baleno', '2012 Maruti Alto 800', '2023 Tata PUNCH', '2016 Hyundai Creta', '2023 Maruti Alto K10', '2019 Maruti Swift', '2015 Hyundai Eon', '2015 Maruti Wagon R 1.0', '2015 Honda Amaze', '2019 Maruti Swift', '2016 Tata Tiago', '2019 Datsun Redi Go', '2019 Maruti Swift', '2016 Hyundai Elite i20', '2015 Honda City', '2014 Hyundai Grand i10', '2018 Datsun Redi Go', '2017 Maruti Wagon R 1.0', '2024 KIA SONET', '2019 Hyundai Grand i10', '2019 MG HECTOR', '2017 Maruti Swift', '2017 Maruti Swift', '2021 Tata PUNCH', '2018 Maruti Wagon R 1.0', '2021 Maruti Swift', '2023 Toyota Glanza', '2019 Ford FREESTYLE', '2017 Renault Kwid', '2016 Maruti Swift', '2022 Maruti Swift', '2019 Tata NEXON', '2022 Tata PUNCH', '2017 Maruti Wagon R 1.0', '2018 Renault Kwid', '2022 Tata NEXON', '2020 Renault TRIBER', '2018 Tata Tiago', '2023 Volkswagen TAIGUN', '2017 Hyundai Creta', '2019 Maruti Baleno', '2012 Maruti Alto 800', '2023 Tata PUNCH', '2016 Hyundai Creta', '2023 Maruti Alto K10', '2023 Toyota Glanza', '2017 Maruti Wagon R 1.0', '2015 Hyundai Creta', '2016 Honda City', '2015 Ford Ecosport', '2022 Tata ALTROZ', '2022 Renault Kwid', '2018 Maruti Celerio X', '2016 Renault Kwid', '2021 Hyundai VENUE', '2023 Maruti XL6', '2015 Hyundai i10', '2017 Maruti Wagon R 1.0', '2018 Tata Tiago', '2017 Honda Jazz', '2019 Tata NEXON', '2020 Renault TRIBER', '2018 Hyundai Grand i10', '2022 Tata TIGOR', '2018 Tata NEXON', '2021 Maruti Swift', '2019 Maruti Swift', '2019 Ford FREESTYLE', '2015 Hyundai Eon', '2017 Renault Kwid', '2016 Maruti Swift', '2022 Maruti Swift', '2015 Maruti Wagon R 1.0', '2019 Tata NEXON', '2015 Honda Amaze', '2022 Tata PUNCH', '2019 Maruti Swift', '2018 Renault Kwid', '2016 Tata Tiago', '2019 Datsun Redi Go', '2019 Maruti Swift', '2022 Tata NEXON', '2016 Hyundai Elite i20', '2020 Renault TRIBER', '2018 Tata Tiago', '2024 Tata PUNCH', '2012 Maruti Wagon R 1.0', '2011 Audi Q5', '2013 Maruti Wagon R 1.0', '2017 Tata Tiago', '2012 Hyundai i10', '2012 Maruti Swift', '2015 Hyundai Eon', '2016 Renault Kwid', '2014 Maruti Alto 800', '2022 Maruti Alto', '2011 Ford Figo', '2016 Renault Kwid', '2015 Hyundai i10', '2013 Maruti Swift Dzire', '2017 Honda City', '2023 Hyundai VENUE', '2017 Hyundai Elite i20', '2020 Hyundai VENUE', '2011 Maruti Wagon R 1.0', '2021 Maruti Swift', '2019 Maruti Swift', '2023 Toyota Glanza', '2019 Ford FREESTYLE', '2015 Hyundai Eon', '2017 Renault Kwid', '2016 Maruti Swift', '2022 Maruti Swift', '2015 Maruti Wagon R 1.0', '2019 Tata NEXON', '2015 Honda Amaze', '2022 Tata PUNCH', '2017 Maruti Wagon R 1.0', '2019 Maruti Swift', '2018 Renault Kwid', '2016 Tata Tiago', '2019 Datsun Redi Go', '2019 Maruti Swift', '2022 Tata NEXON', '2016 Hyundai Elite i20', '2012 Renault Duster', '2013 Maruti Ritz', '2012 Maruti Ritz', '2017 Hyundai Creta', '2012 Toyota Fortuner', '2014 Hyundai i20', '2023 Hyundai Verna', '2011 Hyundai i10', '2017 Mahindra XUV500', '2014 Honda Mobilio', '2020 Maruti Alto', '2022 Renault TRIBER', '2012 Nissan Micra', '2015 Jaguar XF', '2024 Maruti BREZZA', '2018 Renault Duster', '2023 Mahindra SCORPIO-N', '2020 KIA SELTOS', '2017 Toyota Fortuner', '2011 Audi Q7', '2021 Honda Amaze', '2013 Maruti Wagon R 1.0', '2015 Renault Kwid', '2011 Maruti Wagon R 1.0', '2025 Hyundai NEW I20', '2020 Hyundai Creta', '2013 Nissan Terrano', '2017 Tata NEXON', '2017 Maruti Vitara Brezza', '2013 Hyundai Eon', '2018 Tata TIGOR', '2020 Hyundai Elite i20', '2013 Maruti Ritz', '2017 Honda WR-V', '2018 Maruti Vitara Brezza', '2021 MG HECTOR PLUS', '2021 Jeep Compass', '2021 Tata Tiago', '2018 Maruti Wagon R 1.0', '2019 Maruti Baleno', '2023 Maruti Baleno', '2016 Ford Figo Aspire', '2021 Tata NEXON', '2014 Honda Amaze', '2020 Maruti S PRESSO', '2021 Tata Tiago', '2020 Tata Tiago', '2021 Hyundai GRAND I10 NIOS', '2017 Hyundai Elite i20', '2019 Honda Amaze', '2019 Tata NEXON', '2023 MG ASTOR', '2016 Maruti Alto 800', '2022 Nissan MAGNITE', '2017 Maruti Baleno', '2014 Hyundai Grand i10', '2022 Skoda SLAVIA', '2013 Renault Duster', '2023 Tata NEXON', '2015 Maruti Swift', '2017 Hyundai Creta', '2013 Nissan Sunny', '2018 Mahindra XUV500', '2018 Maruti Swift', '2017 Maruti Swift Dzire', '2012 Hyundai i10', '2013 Nissan Sunny', '2013 Maruti Alto K10', '2012 Renault Duster', '2019 Mahindra MARAZZO', '2019 Honda Amaze', '2022 Tata PUNCH', '2014 Ford Ecosport', '2017 Maruti Vitara Brezza', '2011 Maruti Alto K10', '2023 Maruti New Wagon-R', '2022 KIA SONET', '2021 Maruti Swift', '2017 Renault Kwid', '2016 Maruti Swift', '2018 Renault Kwid', '2017 Hyundai Creta', '2015 Maruti Swift Dzire', '2018 Hyundai Grand i10', '2023 Tata PUNCH', '2019 Renault TRIBER', '2023 KIA CARENS', '2016 Toyota Corolla Altis', '2021 Maruti New Wagon-R', '2024 Tata ALTROZ', '2017 Datsun Redi Go', '2023 Toyota URBAN CRUISER HYRYDER', '2017 Jeep Compass', '2016 Maruti Wagon R 1.0', '2015 Maruti Alto 800', '2019 Maruti Swift', '2015 Hyundai i10', '2019 Maruti Swift', '2023 Toyota Glanza', '2019 Ford FREESTYLE', '2015 Hyundai Eon', '2022 Maruti Swift', '2015 Maruti Wagon R 1.0', '2019 Tata NEXON', '2015 Honda Amaze', '2022 Tata PUNCH', '2017 Maruti Wagon R 1.0', '2019 Maruti Swift', '2016 Tata Tiago', '2019 Datsun Redi Go', '2019 Maruti Swift', '2022 Tata NEXON', '2016 Hyundai Elite i20', '2020 Renault TRIBER', '2018 Tata Tiago', '2023 Volkswagen TAIGUN', '2015 Honda City', '2012 Maruti Wagon R 1.0', '2016 Maruti Alto K10', '2017 Maruti Vitara Brezza', '2016 Maruti Ertiga', '2016 Renault Kwid', '2013 Maruti Alto 800', '2013 Toyota Etios Liva', '2013 Maruti Alto 800', '2013 Hyundai i10', '2013 Maruti Wagon R 1.0', '2020 Renault TRIBER', '2015 Maruti Swift Dzire', '2016 Maruti Vitara Brezza', '2019 Mahindra XUV500', '2015 Renault Duster', '2021 Volkswagen Polo', '2018 Maruti Baleno', '2015 Ford Ecosport', '2020 Mahindra XUV300', '2011 Nissan Sunny', '2016 Mahindra TUV300', '2019 Renault Kwid', '2014 Maruti Wagon R 1.0', '2015 Toyota Corolla Altis', '2020 Tata ALTROZ', '2012 Maruti Wagon R 1.0', '2012 Maruti Wagon R 1.0', '2022 Tata PUNCH', '2012 Maruti Wagon R 1.0', '2012 Maruti Wagon R 1.0', '2017 Honda City', '2016 Renault Kwid', '2018 Tata NEXON', '2013 Maruti Wagon R 1.0', '2014 Toyota Etios', '2013 Maruti Swift Dzire', '2017 Tata TIGOR', '2012 Maruti Wagon R 1.0', '2021 Maruti New Wagon-R', '2020 Hyundai Elite i20', '2013 Maruti Swift Dzire', '2011 Chevrolet Aveo', '2023 Volkswagen TAIGUN', '2013 Honda Brio', '2013 Hyundai Eon', '2020 Mahindra Bolero', '2017 Maruti Swift', '2017 Hyundai Xcent', '2014 Hyundai Eon', '2016 Hyundai Elite i20', '2017 Hyundai Xcent', '2019 Maruti Vitara Brezza', '2011 Hyundai Verna', '2018 Maruti Wagon R 1.0', '2017 Maruti Ertiga', '2013 Maruti Swift Dzire', '2018 Hyundai Eon', '2018 Maruti IGNIS', '2023 Maruti Eeco', '2016 Maruti Celerio', '2021 Maruti New Wagon-R', '2022 Tata NEXON', '2012 Maruti Wagon R 1.0', '2018 Hyundai Grand i10', '2012 Maruti Wagon R 1.0', '2017 Maruti Vitara Brezza', '2012 Maruti Wagon R 1.0', '2012 Maruti Wagon R 1.0', '2018 Maruti Dzire', '2016 Maruti Celerio', '2015 Maruti Wagon R 1.0', '2013 Volkswagen Polo', '2018 Maruti Swift', '2012 Maruti Wagon R 1.0', '2013 Maruti Alto K10', '2017 Toyota Innova Crysta', '2018 Hyundai NEW SANTRO', '2018 Premier Rio', '2021 Renault Kiger', '2021 Tata ALTROZ', '2012 Maruti Wagon R 1.0', '2024 Tata NEXON', '2023 MG ASTOR', '2012 Maruti Wagon R 1.0', '2018 Renault Kwid', '2012 Maruti Wagon R 1.0', '2016 Maruti Alto 800', '2012 Maruti Wagon R 1.0', '2019 Maruti IGNIS', '2019 Tata Tiago', '2015 Renault Kwid', '2013 Maruti Swift Dzire', '2013 Hyundai Eon', '2015 Maruti Swift', '2012 Hyundai i20', '2013 Maruti Wagon R 1.0', '2018 Maruti Celerio', '2018 Honda Amaze', '2013 Hyundai Eon', '2015 Hyundai Verna', '2023 Tata PUNCH', '2020 Tata Tiago', '2022 Maruti New Wagon-R', '2014 Maruti Wagon R 1.0', '2019 Maruti Swift', '2015 Tata Nano', '2013 Maruti Ertiga', '2015 Ford Figo Aspire', '2014 Maruti Alto 800', '2017 Maruti Dzire', '2014 Maruti Swift Dzire', '2014 Hyundai Eon', '2014 Maruti Wagon R 1.0', '2014 Maruti Wagon R 1.0', '2021 Maruti Ertiga', '2012 Hyundai Eon', '2015 Hyundai i10', '2015 Datsun Go Plus', '2016 Tata Indica EV2', '2014 Maruti Celerio', '2021 Maruti Swift', '2019 Maruti Swift', '2023 Toyota Glanza', '2019 Ford FREESTYLE', '2015 Hyundai Eon', '2017 Renault Kwid', '2016 Maruti Swift', '2022 Maruti Swift', '2015 Maruti Wagon R 1.0', '2019 Tata NEXON', '2015 Honda Amaze', '2022 Tata PUNCH', '2017 Maruti Wagon R 1.0', '2019 Maruti Swift', '2018 Renault Kwid', '2016 Tata Tiago', '2019 Datsun Redi Go', '2019 Maruti Swift', '2022 Tata NEXON', '2016 Hyundai Elite i20', '2019 Maruti Swift', '2015 Hyundai Eon', '2015 Maruti Wagon R 1.0', '2015 Honda Amaze', '2019 Maruti Swift', '2016 Tata Tiago', '2019 Datsun Redi Go', '2019 Maruti Swift', '2016 Hyundai Elite i20', '2015 Honda City', '2014 Hyundai Grand i10', '2018 Datsun Redi Go', '2017 Maruti Wagon R 1.0', '2024 KIA SONET', '2019 Hyundai Grand i10', '2019 MG HECTOR', '2017 Maruti Swift', '2017 Maruti Swift', '2021 Tata PUNCH', '2018 Maruti Wagon R 1.0', '2021 Maruti Swift', '2023 Toyota Glanza', '2019 Ford FREESTYLE', '2017 Renault Kwid', '2016 Maruti Swift', '2022 Maruti Swift', '2019 Tata NEXON', '2022 Tata PUNCH', '2017 Maruti Wagon R 1.0', '2018 Renault Kwid', '2022 Tata NEXON', '2020 Renault TRIBER', '2018 Tata Tiago', '2023 Volkswagen TAIGUN', '2017 Hyundai Creta', '2019 Maruti Baleno', '2012 Maruti Alto 800', '2023 Tata PUNCH', '2016 Hyundai Creta', '2023 Maruti Alto K10', '2020 KIA SELTOS', '2017 Hyundai Grand i10', '2015 Maruti Swift', '2024 Renault TRIBER', '2018 Maruti Vitara Brezza', '2016 Datsun Redi Go', '2015 Nissan Sunny', '2016 Maruti Vitara Brezza', '2013 Maruti Ertiga', '2021 KIA SONET', '2013 Maruti Swift', '2017 Renault Kwid', '2015 Hyundai Creta', '2016 Hyundai Elite i20', '2014 Hyundai Verna', '2011 Volkswagen Polo', '2018 Hyundai Creta', '2016 Hyundai Elite i20', '2019 Nissan Kicks', '2016 Maruti Baleno', '2023 Toyota Glanza', '2017 Maruti Wagon R 1.0', '2015 Hyundai Creta', '2016 Honda City', '2015 Ford Ecosport', '2022 Tata ALTROZ', '2022 Renault Kwid', '2018 Maruti Celerio X', '2016 Renault Kwid', '2021 Hyundai VENUE', '2023 Maruti XL6', '2015 Hyundai i10', '2017 Maruti Wagon R 1.0', '2018 Tata Tiago', '2017 Honda Jazz', '2019 Tata NEXON', '2020 Renault TRIBER', '2018 Hyundai Grand i10', '2022 Tata TIGOR', '2018 Tata NEXON', '2021 Maruti Swift', '2019 Maruti Swift', '2019 Ford FREESTYLE', '2015 Hyundai Eon', '2017 Renault Kwid', '2016 Maruti Swift', '2022 Maruti Swift', '2015 Maruti Wagon R 1.0', '2019 Tata NEXON', '2015 Honda Amaze', '2022 Tata PUNCH', '2019 Maruti Swift', '2018 Renault Kwid', '2016 Tata Tiago', '2019 Datsun Redi Go', '2019 Maruti Swift', '2022 Tata NEXON', '2016 Hyundai Elite i20', '2020 Renault TRIBER', '2018 Tata Tiago', '2012 Maruti Alto 800', '2014 Tata Zest', '2020 Ford Ecosport', '2020 Maruti Vitara Brezza', '2015 Hyundai Elite i20', '2022 Hyundai VENUE', '2019 Toyota Innova Crysta', '2012 Maruti Wagon R 1.0', '2016 Maruti S Cross', '2013 Maruti Wagon R 1.0', '2020 Hyundai GRAND I10 NIOS', '2019 Maruti Swift', '2014 Maruti Ertiga', '2015 Hyundai Eon', '2012 Hyundai i10', '2017 Maruti Alto 800', '2025 Maruti New Wagon-R', '2016 Maruti Alto 800', '2023 Hyundai VENUE', '2015 Honda Amaze', '2022 Maruti Swift', '2016 Maruti Wagon R 1.0', '2015 Datsun Go Plus', '2017 Tata Tiago', '2018 Honda Amaze', '2015 Maruti Swift', '2022 Tata ALTROZ', '2013 Maruti Alto 800', '2015 Datsun Go Plus', '2022 Maruti Celerio', '2018 Maruti Swift', '2022 Maruti Baleno', '2013 Hyundai Santro Xing', '2018 Maruti Alto K10', '2019 Hyundai NEW SANTRO', '2018 Hyundai Creta', '2018 Maruti Wagon R 1.0', '2024 KIA SONET', '2018 Maruti Vitara Brezza', '2016 Mahindra XUV500', '2022 Tata ALTROZ', '2022 Mahindra XUV700', '2017 Tata TIGOR', '2023 Mahindra Thar', '2015 Hyundai Grand i10', '2016 Maruti Alto 800', '2020 Maruti Alto', '2012 Maruti Wagon R 1.0', '2013 Hyundai i20', '2016 Maruti Alto 800', '2020 Hyundai Creta', '2014 Toyota Etios', '2015 Hyundai Grand i10', '2014 Hyundai Grand i10', '2018 Hyundai Elite i20', '2012 Maruti Ritz', '2017 Maruti Swift Dzire', '2014 Maruti Alto K10', '2012 Hyundai i10', '2017 Renault Kwid', '2012 Renault Duster', '2013 Maruti Ritz', '2012 Maruti Ritz', '2017 Hyundai Creta', '2012 Toyota Fortuner', '2014 Hyundai i20', '2023 Hyundai Verna', '2011 Hyundai i10', '2017 Mahindra XUV500', '2014 Honda Mobilio', '2020 Maruti Alto', '2022 Renault TRIBER', '2012 Nissan Micra', '2015 Jaguar XF', '2024 Maruti BREZZA', '2018 Renault Duster', '2023 Mahindra SCORPIO-N', '2020 KIA SELTOS', '2017 Toyota Fortuner', '2011 Audi Q7', '2021 Honda Amaze', '2013 Maruti Wagon R 1.0', '2015 Renault Kwid', '2011 Maruti Wagon R 1.0', '2025 Hyundai NEW I20', '2020 Hyundai Creta', '2013 Nissan Terrano', '2017 Tata NEXON', '2017 Maruti Vitara Brezza', '2013 Hyundai Eon', '2018 Tata TIGOR', '2020 Hyundai Elite i20', '2013 Maruti Ritz', '2017 Honda WR-V', '2018 Maruti Vitara Brezza', '2021 MG HECTOR PLUS', '2021 Jeep Compass', '2021 Tata Tiago', '2018 Maruti Wagon R 1.0', '2019 Maruti Baleno', '2023 Maruti Baleno', '2016 Ford Figo Aspire', '2021 Tata NEXON', '2014 Honda Amaze', '2020 Maruti S PRESSO', '2021 Tata Tiago', '2020 Tata Tiago', '2021 Hyundai GRAND I10 NIOS', '2017 Hyundai Elite i20', '2019 Honda Amaze', '2019 Tata NEXON', '2023 MG ASTOR', '2016 Maruti Alto 800', '2022 Nissan MAGNITE', '2017 Maruti Baleno', '2014 Hyundai Grand i10', '2022 Skoda SLAVIA', '2013 Renault Duster', '2023 Tata NEXON', '2015 Maruti Swift', '2017 Hyundai Creta', '2013 Nissan Sunny', '2018 Mahindra XUV500', '2018 Maruti Swift', '2017 Maruti Swift Dzire', '2012 Hyundai i10', '2013 Nissan Sunny', '2013 Maruti Alto K10', '2012 Renault Duster', '2019 Mahindra MARAZZO', '2019 Honda Amaze', '2022 Tata PUNCH', '2014 Ford Ecosport', '2017 Maruti Vitara Brezza', '2011 Maruti Alto K10', '2023 Maruti New Wagon-R', '2022 KIA SONET', '2019 Maruti Alto K10', '2016 Maruti Swift', '2015 Renault Kwid', '2013 Toyota Etios Liva', '2019 Maruti Swift', '2013 Nissan Micra', '2015 Ford Ecosport', '2019 Mahindra MARAZZO', '2014 Maruti Swift', '2018 Hyundai Verna', '2012 Renault Duster', '2015 Maruti Swift', '2014 Honda City', '2017 Tata NEXON', '2023 Maruti Ertiga', '2017 Maruti S Cross', '2011 Hyundai i20', '2014 Honda Amaze', '2015 Honda Amaze', '2017 Tata Tiago', '2023 KIA SELTOS', '2015 Volkswagen Polo', '2011 Toyota Etios', '2014 Toyota Innova', '2016 Maruti Vitara Brezza', '2020 Hyundai VENUE', '2016 Renault Kwid', '2025 Maruti Swift', '2019 Renault Kwid', '2016 Maruti Alto K10', '2012 Renault Duster', '2012 Hyundai New Elantra', '2021 Maruti XL6', '2012 Volkswagen Polo', '2020 Hyundai GRAND I10 NIOS', '2016 Maruti Swift', '2017 Volvo S60', '2014 Hyundai Santro Xing', '2014 Datsun Go', '2018 Renault Kwid', '2019 Ford FREESTYLE', '2022 Tata PUNCH', '2020 Renault TRIBER', '2016 Hyundai Creta', '2023 Maruti Alto K10', '2022 Skoda SLAVIA', '2024 MG HECTOR PLUS', '2017 Datsun Redi Go', '2015 Honda City', '2022 Honda City', '2022 MG HECTOR', '2018 Jeep Compass', '2023 Maruti BREZZA', '2020 Tata Tiago', '2016 Maruti Baleno', '2016 Hyundai Creta', '2017 Tata Tiago', '2016 Hyundai Creta', '2023 Mahindra Thar', '2021 Renault TRIBER', '2021 Maruti Swift', '2019 Maruti Swift', '2023 Toyota Glanza', '2015 Hyundai Eon', '2017 Renault Kwid', '2016 Maruti Swift', '2022 Maruti Swift', '2015 Maruti Wagon R 1.0', '2019 Tata NEXON', '2015 Honda Amaze', '2017 Maruti Wagon R 1.0', '2019 Maruti Swift', '2018 Renault Kwid', '2016 Tata Tiago', '2019 Datsun Redi Go', '2019 Maruti Swift', '2022 Tata NEXON', '2016 Hyundai Elite i20', '2018 Tata Tiago', '2023 Volkswagen TAIGUN', '2011 Maruti Alto', '2019 Ford New Figo', '2011 Nissan Sunny', '2018 Jeep Compass', '2021 Maruti Swift', '2025 Maruti Dzire', '2017 Maruti Dzire', '2013 Hyundai Eon', '2013 Maruti Wagon R 1.0', '2012 Hyundai i10', '2013 Maruti Swift Dzire', '2015 Hyundai Elite i20', '2015 Honda Amaze', '2016 Maruti Wagon R 1.0', '2013 Maruti Swift Dzire', '2018 Premier Rio', '2012 Maruti Wagon R 1.0', '2018 Maruti Dzire', '2011 Maruti Alto', '2021 Hyundai NEW I20', '2023 Maruti FRONX', '2020 Hyundai VENUE', '2022 Mahindra Thar', '2017 Ford Ecosport', '2011 Maruti Wagon R 1.0', '2012 Maruti Wagon R 1.0', '2016 Maruti Alto K10', '2017 Maruti Vitara Brezza', '2016 Maruti Ertiga', '2016 Renault Kwid', '2013 Maruti Alto 800', '2013 Toyota Etios Liva', '2013 Maruti Alto 800', '2013 Hyundai i10', '2013 Maruti Wagon R 1.0', '2020 Renault TRIBER', '2015 Maruti Swift Dzire', '2016 Maruti Vitara Brezza', '2019 Mahindra XUV500', '2015 Renault Duster', '2021 Volkswagen Polo', '2018 Maruti Baleno', '2015 Ford Ecosport', '2020 Mahindra XUV300', '2011 Nissan Sunny', '2021 Maruti New Wagon-R', '2022 Tata NEXON', '2012 Maruti Wagon R 1.0', '2018 Hyundai Grand i10', '2012 Maruti Wagon R 1.0', '2017 Maruti Vitara Brezza', '2012 Maruti Wagon R 1.0', '2012 Maruti Wagon R 1.0', '2018 Maruti Dzire', '2016 Maruti Celerio', '2015 Maruti Wagon R 1.0', '2013 Volkswagen Polo', '2018 Maruti Swift', '2012 Maruti Wagon R 1.0', '2013 Maruti Alto K10', '2017 Toyota Innova Crysta', '2018 Hyundai NEW SANTRO', '2018 Premier Rio', '2021 Renault Kiger', '2021 Tata ALTROZ', '2015 Hyundai Eon', '2014 Hyundai Eon', '2024 KIA SONET', '2020 Maruti Eeco', '2016 Maruti Wagon R 1.0', '2021 Maruti New Wagon-R', '2011 Maruti Wagon R 1.0', '2014 Hyundai i10', '2015 Ford New Figo', '2017 Hyundai Grand i10', '2024 Hyundai VENUE', '2016 Maruti Swift Dzire', '2017 Honda Amaze', '2016 Maruti Alto K10', '2016 Maruti Vitara Brezza', '2018 Mahindra XUV500', '2018 Mahindra KUV 100 NXT', '2018 Maruti Swift Dzire', '2015 Renault Duster', '2013 Maruti Wagon R Stingray', '2023 Tata PUNCH', '2020 Tata Tiago', '2022 Maruti New Wagon-R', '2014 Maruti Wagon R 1.0', '2019 Maruti Swift', '2015 Tata Nano', '2013 Maruti Ertiga', '2015 Ford Figo Aspire', '2014 Maruti Alto 800', '2017 Maruti Dzire', '2014 Maruti Swift Dzire', '2014 Hyundai Eon', '2014 Maruti Wagon R 1.0', '2014 Maruti Wagon R 1.0', '2021 Maruti Ertiga', '2012 Hyundai Eon', '2015 Hyundai i10', '2015 Datsun Go Plus', '2016 Tata Indica EV2', '2014 Maruti Celerio', '2016 Hyundai Elite i20', '2008 Toyota Innova', '2017 Maruti Celerio X', '2015 Hyundai i20 Active', '2016 Hyundai Creta', '2013 Maruti Alto 800', '2020 KIA SELTOS', '2023 Mahindra XUV300', '2016 Maruti Baleno', '2023 Tata Tiago', '2013 Volvo V40 Cross Country', '2021 MG HECTOR PLUS', '2017 Hyundai Xcent', '2018 Hyundai Xcent', '2024 Toyota Glanza', '2017 Honda Amaze', '2018 Mahindra XUV500', '2022 Hyundai GRAND I10 NIOS', '2016 Maruti Wagon R 1.0', '2017 Hyundai Grand i10', '2013 Maruti Swift Dzire', '2016 Maruti Swift Dzire', '2017 Maruti Swift', '2013 Volkswagen Polo', '2018 Maruti Swift', '2015 Honda City', '2013 Hyundai Eon', '2017 Mahindra KUV 100 NXT', '2016 Maruti Wagon R 1.0', '2013 Hyundai i20', '2020 Mahindra Bolero', '2012 Hyundai i10', '2018 Honda Amaze', '2012 Toyota Etios', '2017 Honda Amaze', '2020 Tata ALTROZ', '2017 Maruti Swift Dzire', '2015 Hyundai Creta', '2015 Hyundai Creta', '2014 Hyundai i10', '2023 Tata PUNCH', '2021 Maruti Alto', '2014 Maruti Alto 800', '2016 Mahindra Kuv100', '2021 Tata NEXON', '2015 Hyundai Grand i10', '2020 Tata NEXON', '2012 Hyundai Ver

In [12]:
print("Car Name:",len(product_name))
print("-"*150)
print("Kilometers:",len(km))
print("-"*150)
print("Fuel:",len(fuel))
print("-"*150)
print("Transmission:",len(transmission))
print("-"*150)
print("Registration:",len(registration))
print("-"*150)
print("EMI:",len(emis))
print("-"*150)
#print("Original Price:",len(original_prices))
#print("-"*150)
print("Final Price:",len(final_prices))
print("-"*150)
print("Location:",len(locations))

Car Name: 955
------------------------------------------------------------------------------------------------------------------------------------------------------
Kilometers: 955
------------------------------------------------------------------------------------------------------------------------------------------------------
Fuel: 955
------------------------------------------------------------------------------------------------------------------------------------------------------
Transmission: 890
------------------------------------------------------------------------------------------------------------------------------------------------------
Registration: 773
------------------------------------------------------------------------------------------------------------------------------------------------------
EMI: 3938
------------------------------------------------------------------------------------------------------------------------------------------------------
Final Price: 1198
------------------------------------------------------------------------------------------------------------------------------------------------------
Location: 1969

In [13]:
min_len_list=[
    len(product_name),
    len(emis),
    len(km),
    len(fuel),
    len(transmission),
    len(registration),
    #len(original_prices),
    len(final_prices),
    len(locations) ]
min_len = min(min_len_list)
print(min_len)
df=pd.DataFrame({
    "Car Name":product_name[:min_len],
    "Kilometers":km[:min_len],
    "Fuel":fuel[:min_len],
    "Transmission":transmission[:min_len],
    "Registration":registration[:min_len],
    "EMI":emis[:min_len],
    #"Original Price":original_prices[:min_len],
    "Final Price":final_prices[:min_len],
    "Location":locations[:min_len]
})
df.shape

773

(773, 8)

In [14]:
df.head()

,Car Name,Kilometers,Fuel,Transmission,Registration,EMI,Final Price,Location
0,2019 Maruti Swift,58358,CNG,Manual,DL-11,"EMI ₹8,120/m*",Account,"Gaur City mall, Multilevel parking, Greater N..."
1,2015 Hyundai Eon,43518,Petrol,Manual,DL-13,₹5.33L₹4.60 lakh+ other charges,₹4.05 lakh,"Metro Walk, Rohini, New Delhi"
2,2015 Maruti Wagon R 1.0,65974,CNG,Manual,DL-12,"EMI ₹7,918/m*",₹1.77 lakh,"Piyush Mahendra Mall, opp. Dussehra Ground, N..."
3,2015 Honda Amaze,40807,Petrol,Manual,DL-14,₹4.40L₹4.05 lakh+ other charges,₹2.13 lakh,"GNB Mall, Raj Nagar Extension, Ghaziabad"
4,2019 Maruti Swift,57241,Petrol,Manual,DL-12,"EMI ₹8,826/m*",₹2.35 lakh,"Radisson Blu, Sector 13, Dwarka, New Delhi"

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df['Car Name'].value_counts()

Car Name
2019 Maruti Swift          31
2012 Maruti Wagon R 1.0    20
2017 Maruti Wagon R 1.0    14
2019 Tata NEXON            13
2016 Hyundai Elite i20     12
                           ..
2014 Toyota Innova          1
2025 Maruti Swift           1
2023 Maruti FRONX           1
2022 Mahindra Thar          1
2017 Ford Ecosport          1
Name: count, Length: 259, dtype: int64

In [17]:
df['EMI'].value_counts()

EMI
Not available on EMI         16
EMI ₹6,443/m*                 8
EMI ₹6,620/m*                 8
EMI ₹5,517/m*                 7
₹3.65 lakh+ other charges     7
                             ..
EMI ₹12,357/m*                1
₹1.66 lakh                    1
EMI ₹3,937/m*                 1
₹2.29L₹2.23 lakh              1
EMI ₹9,596/m*                 1
Name: count, Length: 388, dtype: int64

In [18]:
df.to_csv('cars_data.csv', index=False)
print("DataFrame saved to 'cars_data.csv'")

from google.colab import files
files.download('cars_data.csv')

DataFrame saved to 'cars_data.csv'